language: node_js
node_js:
  - "11.15"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - npm install
  - npm run build
  - npm test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

